version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bestNiania
        ports:
            - "9000:9000"
        environment:
            - VIRTUAL_HOST=best-niania.local
            - SERVICE_NAME=app
            - SERVICE_TAGS=dev
        volumes:
            - .:/var/www/html
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: bestNiania-webserver
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bestNiania-phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        networks:
            - app-network

    db:
        image: mysql:5.7.32
        container_name: bestNiania-db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=best_niania
            - MYSQL_ROOT_PASSWORD=123
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
